[package]
name = "svg-renderer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
palette = "0.5.0"
resvg = "0.14.0"
rocket = "0.5.0-rc.1"
tiny-skia = "0.5.1"
usvg = "0.14.0"
